(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";var src_1=require("../src");src_1.documentScript();
},{"../src":11}],2:[function(require,module,exports){
"use strict";var Expression=function(){function s(s){this.type="CallExpression",this.arguments=[],this.name=s}return s.prototype.insertArg=function(s){this.arguments.push(s)},s}();exports.Expression=Expression;
},{}],3:[function(require,module,exports){
"use strict";var Variable=function(){function a(a,e){this.name=a,this.value=e}return a}();exports.Variable=Variable;
},{}],4:[function(require,module,exports){
"use strict";function createExpression(e,r,n){var t=new _1.Expression(EXP_NAME),a=r.shift();elementExec(a,t,"source");var s=r.shift();"to"===s.value?t.insertArg(new parser_1.Keyword(s.value)):utils_1.errorHandler.typeError('A keyword must be followed after srouce element when using "append".');var o=r.shift();elementExec(o,t,"target"),n.insertExpression(t)}function elementExec(e,r,n){!parser_1.isKeyword(e.value)&&_1.EXPRESSION_LIST.indexOf(e.value)<0?r.insertArg("number"===e.type?new parser_2.NumberLiteral(e.value):new parser_2.StringLiteral(e.value)):utils_1.errorHandler.typeError("You can't use a keyword or expression as the name of "+n+' element when calling "append".')}function run(e){var r=e.arguments.shift().value,n=transformer_1.VARIABLE_HASH[r].value;void 0===n&&utils_1.errorHandler.undefinedError(r+" is undefined."),("object"!=typeof n||void 0===n.nodeName&&void 0===n.nodeType)&&utils_1.errorHandler.typeError(r+" isn't a HTML Element.");var t=e.arguments.shift();"keyword"===t.type&&"to"===t.value||utils_1.errorHandler.syntaxError('"to" must be followed after "${variableName}" in "append" expression.');var a=e.arguments.shift().value,s=transformer_1.VARIABLE_HASH[a].value;void 0===s&&utils_1.errorHandler.undefinedError("${targetVariable} is undefined."),("object"!=typeof s||void 0===s.nodeName&&void 0===s.nodeType)&&utils_1.errorHandler.typeError(r+" isn't a HTML Element."),expFunc(n,s)}function expFunc(e,r){r.appendChild(e)}var parser_1=require("../../parser"),_1=require("../"),parser_2=require("../../parser"),transformer_1=require("../../transformer"),utils_1=require("../../utils"),EXP_NAME="append";exports.createExpression=createExpression,exports.run=run,exports.expFunc=expFunc;
},{"../":10,"../../parser":15,"../../transformer":18,"../../utils":20}],5:[function(require,module,exports){
"use strict";function createExpression(r,e,a){var t=new _1.Expression(EXP_NAME),s=e.shift();"word"===s.type?t.insertArg(new parser_2.StringLiteral(s.value)):utils_1.errorHandler.typeError("A HTML tag name can't be a number.");var n=e.shift();"as"===n.value?t.insertArg(new parser_1.Keyword(n.value)):utils_1.errorHandler.typeError('A keyword "as" must be provided after HTML tag name in "'+EXP_NAME+'" expression.');var i=e.shift();!parser_1.isKeyword(i.value)&&_1.EXPRESSION_LIST.indexOf(i.value)<0?t.insertArg("number"===i.type?new parser_2.NumberLiteral(i.value):new parser_2.StringLiteral(i.value)):utils_1.errorHandler.typeError("You can't use a keyword or expression as a variable when calling \""+EXP_NAME+'".'),a.insertExpression(t)}function run(r){var e=r.arguments.shift();"StringLiteral"===e.type&&"string"==typeof e.value||utils_1.errorHandler.typeError("You must use a string as your tag name.");var a=r.arguments.shift();"keyword"===a.type&&"as"===a.value||utils_1.errorHandler.syntaxError('"as" must be followed after "${tagName}" in "create" expression.');var t=r.arguments.shift().value,s=document.createElement(e.value);expFunc(t,new _1.Variable(t,s))}function expFunc(r,e){transformer_1.VARIABLE_HASH[r]=e}var parser_1=require("../../parser"),_1=require("../"),parser_2=require("../../parser"),transformer_1=require("../../transformer"),utils_1=require("../../utils"),EXP_NAME="create";exports.createExpression=createExpression,exports.run=run,exports.expFunc=expFunc;
},{"../":10,"../../parser":15,"../../transformer":18,"../../utils":20}],6:[function(require,module,exports){
"use strict";function createExpression(r,e,n){var s=new _1.Expression(EXP_NAME),a=e.shift();!parser_1.isKeyword(a.value)&&_1.EXPRESSION_LIST.indexOf(a.value)<0?s.insertArg("number"===a.type?new parser_2.NumberLiteral(a.value):new parser_2.StringLiteral(a.value)):utils_1.errorHandler.typeError("An element variable can not be a keyword or expression.");var i=e.shift();_1.EXPRESSION_LIST.indexOf(i.value)>-1?s.insertArg(new parser_2.ExpressionLiteral(i.value)):utils_1.errorHandler.throwError("[Unknown Expression] Sadly I don't know the expression called \""+i.value+'". :(');var t=[e.shift(),e.shift()];t.forEach(function(r){return s.insertArg("number"===r.type?new parser_2.NumberLiteral(r.value):new parser_2.StringLiteral(r.value))}),n.insertExpression(s)}function run(r){var e=r.arguments.shift().value,n=transformer_1.VARIABLE_HASH[e].value;if(void 0===n&&utils_1.errorHandler.undefinedError(e+" is undefined."),n.length){var s=r.arguments.shift();if(s.value){"expression"!==s.type&&utils_1.errorHandler.typeError('An expression must be followed after each in "each" expression.');var a=Array.prototype.slice.call(n);a.forEach(function(n){var a=new _1.Expression(s.value),i=e+"_"+utils_1.uidGen(),t=new _1.Variable(i,n);transformer_1.VARIABLE_HASH[i]=t,a.insertArg(new parser_2.StringLiteral(i)),r.arguments.forEach(function(r){return a.insertArg(r)}),expressions[s.value]&&expressions[s.value].run(a)})}}}var parser_1=require("../../parser"),_1=require("../"),expressions=require("../"),parser_2=require("../../parser"),transformer_1=require("../../transformer"),utils_1=require("../../utils"),EXP_NAME="each";exports.createExpression=createExpression,exports.run=run;
},{"../":10,"../../parser":15,"../../transformer":18,"../../utils":20}],7:[function(require,module,exports){
"use strict";function createExpression(e,r,n){var s=new _1.Expression(EXP_NAME),a=r.shift();!parser_1.isKeyword(a.value)&&_1.EXPRESSION_LIST.indexOf(a.value)<0?s.insertArg("number"===a.type?new parser_2.NumberLiteral(a.value):new parser_2.StringLiteral(a.value)):utils_1.errorHandler.typeError("You can't use a keyword or expression as a variable when calling \""+EXP_NAME+'".'),n.insertExpression(s)}function run(e){var r=e.arguments.shift().value,n=transformer_1.VARIABLE_HASH[r].value;void 0===n&&utils_1.errorHandler.undefinedError(r+" is undefined."),("object"!=typeof n||void 0===n.nodeName&&void 0===n.nodeType)&&utils_1.errorHandler.typeError(r+" isn't a HTML Element.");var s=n.parentElement;expFunc(s,n)}function expFunc(e,r){e.removeChild(r)}var parser_1=require("../../parser"),_1=require("../"),parser_2=require("../../parser"),transformer_1=require("../../transformer"),utils_1=require("../../utils"),EXP_NAME="remove";exports.createExpression=createExpression,exports.run=run,exports.expFunc=expFunc;
},{"../":10,"../../parser":15,"../../transformer":18,"../../utils":20}],8:[function(require,module,exports){
"use strict";function createExpression(r,e,s){var a=new _1.Expression(EXP_NAME),t=e.shift();a.insertArg(new parser_2.StringLiteral(t.value.toString()));var n=e.shift();"as"===n.value?a.insertArg(new parser_1.Keyword(n.value)):utils_1.errorHandler.typeError('A keyword "as" must be provided after HTML tag name in "'+EXP_NAME+'" expression.');var i=e.shift();!parser_1.isKeyword(i.value)&&_1.EXPRESSION_LIST.indexOf(i.value)<0?a.insertArg("number"===i.type?new parser_2.NumberLiteral(i.value):new parser_2.StringLiteral(i.value)):utils_1.errorHandler.typeError("You can't use a keyword or expression as a variable when calling \""+EXP_NAME+'".'),s.insertExpression(a)}function run(r){var e=r.arguments.shift();"StringLiteral"===e.type&&"string"==typeof e.value||utils_1.errorHandler.typeError("You must use a string as your selector.");var s=null,a=document.querySelectorAll(e.value);1===a.length?s=a[0]:a.length>1&&(s=a);var t=r.arguments.shift();"keyword"===t.type&&"as"===t.value||utils_1.errorHandler.syntaxError('"as" must be followed after "${tagName}" in "create" expression.');var n=r.arguments.shift().value,i=s;expFunc(n,new _1.Variable(n,i))}function expFunc(r,e){transformer_1.VARIABLE_HASH[r]=e}var parser_1=require("../../parser"),_1=require("../"),parser_2=require("../../parser"),transformer_1=require("../../transformer"),utils_1=require("../../utils"),EXP_NAME="select";exports.createExpression=createExpression,exports.run=run,exports.expFunc=expFunc;
},{"../":10,"../../parser":15,"../../transformer":18,"../../utils":20}],9:[function(require,module,exports){
"use strict";function createExpression(r,e,t){var s=new _1.Expression(EXP_NAME),i=e.shift();!parser_1.isKeyword(i.value)&&_1.EXPRESSION_LIST.indexOf(i.value)<0?s.insertArg("number"===i.type?new parser_2.NumberLiteral(i.value):new parser_2.StringLiteral(i.value)):utils_1.errorHandler.typeError("You can't use a keyword or expression as a variable when calling \""+EXP_NAME+'".');var n=e.shift();"word"===n.type?s.insertArg(new parser_2.StringLiteral(n.value)):utils_1.errorHandler.typeError("A css style properity must be a string.");var a=e.shift();s.insertArg(new parser_2.StringLiteral(a.value)),t.insertExpression(s)}function run(r){var e=r.arguments.shift().value,t=transformer_1.VARIABLE_HASH[e].value;void 0===t&&utils_1.errorHandler.undefinedError(e+" is undefined."),("object"!=typeof t||void 0===t.nodeName&&void 0===t.nodeType)&&utils_1.errorHandler.typeError(e+" isn't a HTML Element.");var s=r.arguments.shift(),i=s.value;"StringLiteral"===s.type&&"string"==typeof i||utils_1.errorHandler.typeError('CSS properity is string-typed. "'+i+'" is not a string.');var n=r.arguments.shift().value;expFunc(t,i,n)}function expFunc(r,e,t){r.style[e]=t}var parser_1=require("../../parser"),_1=require("../"),parser_2=require("../../parser"),transformer_1=require("../../transformer"),utils_1=require("../../utils"),EXP_NAME="style";exports.createExpression=createExpression,exports.run=run;
},{"../":10,"../../parser":15,"../../transformer":18,"../../utils":20}],10:[function(require,module,exports){
"use strict";var append=require("./expressions/exp.append");exports.append=append;var create=require("./expressions/exp.create");exports.create=create;var each=require("./expressions/exp.each");exports.each=each;var remove=require("./expressions/exp.remove");exports.remove=remove;var select=require("./expressions/exp.select");exports.select=select;var style=require("./expressions/exp.style");exports.style=style;var class_Expression_1=require("./class.Expression");exports.Expression=class_Expression_1.Expression;var class_Variable_1=require("./class.Variable");exports.Variable=class_Variable_1.Variable,exports.EXPRESSION_LIST=["append","create","each","remove","select","style"];
},{"./class.Expression":2,"./class.Variable":3,"./expressions/exp.append":4,"./expressions/exp.create":5,"./expressions/exp.each":6,"./expressions/exp.remove":7,"./expressions/exp.select":8,"./expressions/exp.style":9}],11:[function(require,module,exports){
"use strict";function documentScript(){var r=Array.prototype.slice.call(document.querySelectorAll("script[lang=DocumentScript]"));r.forEach(function(r){var e=r.textContent.trim();transformer_1.transformer(parser_1.parser(tokenizer_1.tokenizer(e)))})}var tokenizer_1=require("./tokenizer"),parser_1=require("./parser"),transformer_1=require("./transformer");exports.documentScript=documentScript;
},{"./parser":15,"./tokenizer":17,"./transformer":18}],12:[function(require,module,exports){
"use strict";var AST=function(){function t(t,i){void 0===t&&(t=""),void 0===i&&(i=[]),this.type=t,this.body=i}return t.prototype.insertExpression=function(t){this.body.push(t)},t}();exports.AST=AST;
},{}],13:[function(require,module,exports){
"use strict";function isKeyword(r){return KEYWORD_LIST.indexOf(r)>-1}var KEYWORD_LIST=["as","to","from"],Keyword=function(){function r(r){this.type="keyword",this.value=r}return r}();exports.Keyword=Keyword,exports.isKeyword=isKeyword;
},{}],14:[function(require,module,exports){
"use strict";var __extends=this&&this.__extends||function(t,r){function e(){this.constructor=t}for(var i in r)r.hasOwnProperty(i)&&(t[i]=r[i]);t.prototype=null===r?Object.create(r):(e.prototype=r.prototype,new e)},Literal=function(){function t(t,r){this.type=t,this.value=r}return t}();exports.Literal=Literal;var NumberLiteral=function(t){function r(r){t.call(this,"NumberLiteral",r)}return __extends(r,t),r}(Literal);exports.NumberLiteral=NumberLiteral;var StringLiteral=function(t){function r(r){t.call(this,"StringLiteral",r)}return __extends(r,t),r}(Literal);exports.StringLiteral=StringLiteral;var ExpressionLiteral=function(t){function r(r){t.call(this,"expression",r)}return __extends(r,t),r}(Literal);exports.ExpressionLiteral=ExpressionLiteral;
},{}],15:[function(require,module,exports){
"use strict";function parser(r){if(void 0===r&&(r=[]),!r.length)return!1;for(var e=new class_AST_1.AST("Expression");r.length>0;){var s=r.shift();if("word"===s.type){var a=s.value;expressions[a]&&expressions[a].createExpression(s,r,e)}}return e}var class_AST_1=require("./class.AST");exports.AST=class_AST_1.AST;var class_Keyword_1=require("./class.Keyword");exports.Keyword=class_Keyword_1.Keyword,exports.isKeyword=class_Keyword_1.isKeyword;var class_Literal_1=require("./class.Literal");exports.Literal=class_Literal_1.Literal,exports.NumberLiteral=class_Literal_1.NumberLiteral,exports.StringLiteral=class_Literal_1.StringLiteral,exports.ExpressionLiteral=class_Literal_1.ExpressionLiteral;var expressions=require("../expressions");exports.parser=parser;
},{"../expressions":10,"./class.AST":12,"./class.Keyword":13,"./class.Literal":14}],16:[function(require,module,exports){
"use strict";var __extends=this&&this.__extends||function(e,n){function t(){this.constructor=e}for(var o in n)n.hasOwnProperty(o)&&(e[o]=n[o]);e.prototype=null===n?Object.create(n):(t.prototype=n.prototype,new t)},Token=function(){function e(e,n){void 0===e&&(e=""),this.type=e,this.value=n}return e}();exports.Token=Token;var NumberToken=function(e){function n(n){e.call(this,"number",n)}return __extends(n,e),n}(Token);exports.NumberToken=NumberToken;var WordToken=function(e){function n(n){e.call(this,"word",n)}return __extends(n,e),n}(Token);exports.WordToken=WordToken;
},{}],17:[function(require,module,exports){
"use strict";function tokenizer(e){return e.split(/\s+/).filter(function(e){return e.length>0}).map(function(e){return isNaN(parseInt(e,0))?new class_Token_1.WordToken(e):new class_Token_1.NumberToken(e)})}var class_Token_1=require("./class.Token");exports.Token=class_Token_1.Token,exports.NumberToken=class_Token_1.NumberToken,exports.WordToken=class_Token_1.WordToken,exports.tokenizer=tokenizer;
},{"./class.Token":16}],18:[function(require,module,exports){
"use strict";function transformer(r){r&&r.body.forEach(function(r){expressions[r.name]&&expressions[r.name].run(r)})}var tf_variable_hash_1=require("./tf.variable-hash");exports.VARIABLE_HASH=tf_variable_hash_1.VARIABLE_HASH,exports.TEMP_VARIABLE_HASH=tf_variable_hash_1.TEMP_VARIABLE_HASH;var expressions=require("../expressions");exports.transformer=transformer;
},{"../expressions":10,"./tf.variable-hash":19}],19:[function(require,module,exports){
"use strict";exports.VARIABLE_HASH={},exports.TEMP_VARIABLE_HASH={};
},{}],20:[function(require,module,exports){
"use strict";var errorHandler=require("./util.throw-error");exports.errorHandler=errorHandler;var util_uid_gen_1=require("./util.uid-gen");exports.uidGen=util_uid_gen_1.uidGen;
},{"./util.throw-error":21,"./util.uid-gen":22}],21:[function(require,module,exports){
"use strict";function throwError(r){throw new Error(r)}function typeError(r){throwError("[TypeError] "+r)}function syntaxError(r){throwError("[Syntax Error] "+r)}function undefinedError(r){throwError("[Undefined] "+r)}exports.throwError=throwError,exports.typeError=typeError,exports.syntaxError=syntaxError,exports.undefinedError=undefinedError;
},{}],22:[function(require,module,exports){
"use strict";function uidGen(){return(Math.floor(1e4*Math.random())*Date.now()).toString(16)}exports.uidGen=uidGen;
},{}]},{},[1])


//# sourceMappingURL=bundle.map